# Generated by Django 5.2.1 on 2025-06-02 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teams', models.ManyToManyField(blank=True, related_name='members', to='attendance.team')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, help_text='General notes for the meeting (absences, blockers, etc.)')),
                ('primary_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='attendance.team')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True)),
                ('engagement', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not at all engaged'), (2, 'Not very engaged'), (3, 'Neutral'), (4, 'Somewhat engaged'), (5, 'Very engaged')], null=True)),
                ('effort', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not at all'), (2, 'Not very'), (3, 'Neutral'), (4, 'Somewhat'), (5, 'High Effort'), (6, 'Low Effort–Exempt')], null=True)),
                ('contribution', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Not at all'), (2, 'Not very'), (3, 'Neutral'), (4, 'Somewhat'), (5, 'A lot')], null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_feedback', to='attendance.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
            ],
            options={
                'unique_together': {('meeting', 'member')},
            },
        ),
    ]
