# Generated by Django 5.2.1 on 2025-06-02 15:26

# attendance/migrations/0002_create_initial_superuser.py

from django.db import migrations
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.hashers import make_password

def create_initial_superuser(apps, schema_editor):
    # Get the historical User model for this migration
    User = apps.get_model("auth", "User")

    username = getattr(settings, "ADMIN_USERNAME", "")
    email    = getattr(settings, "ADMIN_EMAIL", "")
    password = getattr(settings, "ADMIN_PASSWORD", "")

    if not username or not password:
        return

    # If a user with this username already exists, do nothing.
    if User.objects.filter(username=username).exists():
        return

    now = timezone.now()
    # Create a new user instance with required non-null fields, including hashed password
    user = User(
        username=username,
        email=email or "",
        is_staff=True,
        is_superuser=True,
        is_active=True,
        date_joined=now,
        last_login=now,
        password=make_password(password),
    )
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),  # adjust if your initial migration has a different name
    ]

    operations = [
        migrations.RunPython(create_initial_superuser),
    ]
