# Generated by Django 5.2.1 on 2025-06-02 15:26

from django.db import migrations
from django.conf import settings
from django.utils import timezone

def create_initial_superuser(apps, schema_editor):
    # Pull in the historical User model for this migration, not the "live" one.
    User = apps.get_model("auth", "User")

    username = getattr(settings, "ADMIN_USERNAME", "")
    email    = getattr(settings, "ADMIN_EMAIL", "")
    password = getattr(settings, "ADMIN_PASSWORD", "")

    # Only proceed if username + password are present and user doesn't already exist.
    if not username or not password:
        return

    # If a user with this username already exists, do nothing.
    if User.objects.filter(username=username).exists():
        return

    # Create a new user instance with all required non-null fields:
    now = timezone.now()
    user = User(
        username=username,
        email=email or "",
        is_staff=True,
        is_superuser=True,
        is_active=True,
        date_joined=now,
        last_login=now,
    )
    # Use the set_password(...) helper so the password is hashed properly.
    user.set_password(password)
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_superuser),
    ]
