# Generated by Django 5.2.1 on 2025-06-02 15:26

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

def create_initial_superuser(apps, schema_editor):
    User = get_user_model()
    username = getattr(settings, "ADMIN_USERNAME", "")
    email    = getattr(settings, "ADMIN_EMAIL", "")
    password = getattr(settings, "ADMIN_PASSWORD", "")

    if username and password and not User.objects.filter(username=username).exists():
        User.objects.create_superuser(
            username=username,
            email=email or "",
            password=password
        )

class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_superuser),
    ]
